AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template to create an ECR private repository"

Resources:
  EcrRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref AWS::StackName