version = 0.1
[default.deploy.parameters]
stack_name = "fargate-backend-ecs-dev"
resolve_s3 = true
s3_prefix = "fargate-backend-ecs-dev"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []